### ISSUE TITLE
YoloV9 multi-gpu training failed: The module torch.distributed.launch is deprecated

### ISSUE THREAD

**Issue by jdiaz97** [WongKinYiu/yolov9#102]
Hello, I'm training to train with 4 gpus, I get this:

`lib/python3.12/site-packages/torch/distributed/launch.py:183: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[2024-02-27 08:27:26,163] torch.distributed.run: [WARNING] 
[2024-02-27 08:27:26,163] torch.distributed.run: [WARNING] *****************************************
[2024-02-27 08:27:26,163] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-02-27 08:27:26,163] torch.distributed.run: [WARNING] *****************************************`

and after that just a massive text.

I'm using Python 3.12.1, it also happened with 3.10. 
I'm also using Torch 2.2.1

**Comment by jdiaz97** [comment]
My training command is:

python -m torch.distributed.launch --nproc_per_node 48 --master_port 9527 train_dual.py --workers 48 --device 0,1,2,3 --sync-bn --batch 128 --data ../dataset3.yml --img 1024 --cfg models/detect/yolov9-c.yaml --weights yolov9-e.pt --name test --hyp hyp.scratch-high.yaml --min-items 0 --epochs 500 --close-mosaic 40

**Comment by jdiaz97** [comment]
```
train_dual.py: error: unrecognized arguments: --local-rank=3
train_dual.py: error: unrecognized arguments: --local-rank=0
train_dual.py: error: unrecognized arguments: --local-rank=2
train_dual.py: error: unrecognized arguments: --local-rank=1
[2024-02-27 08:43:48,446] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 2) local_rank: 0 (pid: 736444) of binary: /home/.conda/envs/yolov9/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/.conda/envs/yolov9/lib/python3.12/site-packages/torch/distributed/launch.py", line 198, in <module>
    main()
  File "/home/conda/envs/yolov9/lib/python3.12/site-packages/torch/distributed/launch.py", line 194, in main
    launch(args)
  File "/home/.conda/envs/yolov9/lib/python3.12/site-packages/torch/distributed/launch.py", line 179, in launch
    run(args)
  File "/home/.conda/envs/yolov9/lib/python3.12/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/.conda/envs/yolov9/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/yolov9/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_dual.py FAILED
------------------------------------------------------------

```

**Comment by jdiaz97** [comment]
Ok, using python -m torch.distributed.run instead helped me moving forward, just to find another error.
