### ISSUE TITLE
train.triple.py mistakes in training: IndexError: list index out of range

### ISSUE THREAD

**Issue by XUPT-Lxu** [WongKinYiu/yolov9#135]
**run:**train.triple.py
Error Details:
Traceback (most recent call last):
  File "train_triple.py", line 636, in <module>
    main(opt)
  File "train_triple.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "train_triple.py", line 309, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/root/yolov9/utils/loss_tal_triple.py", line 179, in __call__
    feats3 = p[1][2] if isinstance(p, tuple) else p[2]
IndexError: list index out of range

Pls how can I fix this?

**Comment by WongKinYiu** [comment]
You have to create corresponding `model.yaml` which use `TripleDDetect` as prediction head first.

**Comment by XUPT-Lxu** [comment]
Thank you, big brother, I'll try it first.
I used 'modls/detect/yolov9-e.yaml' when I ran train.dual.py, but I can't use it at this time?

**Comment by hy36521** [comment]
I encountered the same problem and would like to know how to solve it
