### ISSUE TITLE
AssertionError in evaluation

### ISSUE THREAD

**Issue by liuliuliu1111** [WongKinYiu/yolov9#147]
Hello everyone, I met the AssertionError when I try to evaluate the model.

(yolo_v9) E:\LYJ\python_code\yolov9-main\yolov9-main>python val_dual.py --data data/coco.yaml --img 640 --batch 32 --conf 0.001 --iou 0.7 --device 0 --weights 'E:\LYJ\python_code\yolov9-main\yolov9-main\yolov9-c.pt' --save-json --name yolov9_c_640_val
val_dual: data=data/coco.yaml, weights=["'E:\\LYJ\\python_code\\yolov9-main\\yolov9-main\\yolov9-c.pt'"], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.7, max_det=300, task=val, device=0, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=True, project=runs\val, name=yolov9_c_640_val, exist_ok=False, half=False, dnn=False, min_items=0
YOLOv5  2024-3-1 Python-3.10.6 torch-1.12.1 CUDA:0 (NVIDIA GeForce RTX 3090, 24575MiB)

Traceback (most recent call last):
  File "E:\LYJ\python_code\yolov9-main\yolov9-main\val_dual.py", line 393, in <module>
    main(opt)
  File "E:\LYJ\python_code\yolov9-main\yolov9-main\val_dual.py", line 366, in main
    run(**vars(opt))
  File "C:\Users\Administrator\anaconda3\envs\yolo_v9\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\LYJ\python_code\yolov9-main\yolov9-main\val_dual.py", line 122, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "E:\LYJ\python_code\yolov9-main\yolov9-main\models\common.py", line 675, in __init__
    pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, paddle, triton = self._model_type(w)
  File "E:\LYJ\python_code\yolov9-main\yolov9-main\models\common.py", line 946, in _model_type
    check_suffix(p, sf)  # checks
  File "E:\LYJ\python_code\yolov9-main\yolov9-main\utils\general.py", line 447, in check_suffix
    assert s in suffix, f"{msg}{f} acceptable suffix is {suffix}"
AssertionError: 'E:\LYJ\python_code\yolov9-main\yolov9-main\yolov9-c.pt' acceptable suffix is ['.pt', '.torchscript', '.onnx', '_openvino_model', '.engine', '.mlmodel', '_saved_model', '.pb', '.tflite', '_edgetpu.tflite', '_web_model', '_paddle_model']

**Comment by liuliuliu1111** [comment]
Emmm, I have figured out this problem, I used '.\yolov9-c.pt' as the tutorial said, but I found that the single quotes should be removed.

**Comment by WongKinYiu** [comment]
'/' or '\\\\'

**Comment by jisoo520521** [comment]
@WongKinYiu 应该是去掉单引号吧 我去掉反应好就解决了
