### ISSUE TITLE
Evolve missing dfl hyperparameter in train_dual.py and train.py

### ISSUE THREAD

**Issue by mkrupczak3** [WongKinYiu/yolov9#149]
Running training with the `--evolve` flag, the system outputs the following error:

```
Traceback (most recent call last):
  File "/hpcuser/yolov9/train_dual.py", line 644, in <module>
    main(opt)
  File "/hpcuser/yolov9/train_dual.py", line 604, in main
    g = np.array([meta[k][0] for k in hyp.keys()])  # gains 0-1
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpcuser/yolov9/train_dual.py", line 604, in <listcomp>
    g = np.array([meta[k][0] for k in hyp.keys()])  # gains 0-1
                  ~~~~^^^
KeyError: 'dfl'
```

The root cause is that the `dfl` hyperparameter is absent in the evolve section of `train.py` and `train_dual.py`.

In the file `hyp.scratch-high.yaml` the `dfl` hyperparameter appears just after `obj_pw`:
https://github.com/WongKinYiu/yolov9/blob/3f272312dc6cdd93c7ba94f05c272532b702144a/data/hyps/hyp.scratch-high.yaml#L13

However, in both `train_dual.py` and `train.py` this hyperparameter is missing under the keys for evolve:
https://github.com/WongKinYiu/yolov9/blob/3f272312dc6cdd93c7ba94f05c272532b702144a/train_dual.py#L556
https://github.com/WongKinYiu/yolov9/blob/3f272312dc6cdd93c7ba94f05c272532b702144a/train.py#L546

**Comment by WongKinYiu** [comment]
Currently YOLOv9 does not support evolve, you may need do some modification.

For example, modify loss gain to adaptive with hyp.
https://github.com/WongKinYiu/yolov9/blob/main/utils/loss_tal_dual.py#L247-L249

**Comment by KoniHD** [comment]
Any updates if `--evolve` works now?
Because for me I can run one generation and after that the script crashes with pretty much the same error.

**Comment by mkrupczak3** [comment]
I was able to get evolve to run with the changes in #150, though with what the author stated I'm not sure if it produced truly optimal results.

**Comment by KoniHD** [comment]
Thank you! I just saw it sorry.
Just curious. I am a newbie to the object detection topic. What do the 3 numbers in
```
'dfl': (1, 1.0, 1.75), # dfl loss gain
```
refer to?

**Comment by mkrupczak3** [comment]
See here: 

https://github.com/WongKinYiu/yolov9/blob/5b1ea9a8b3f0ffe4fe0e203ec6232d788bb3fcff/train.py#L532

**Comment by 4-alok** [comment]
I opened a fresh Google Colab and added the new best.pt from the previous session and want to continue training for another 100 epochs.
```
%cd {HOME}/yolov9

!python train.py \
--batch 16 --epochs 50 --img 640 --device 0 --min-items 0 --close-mosaic 15 \
--data {dataset.location}/data.yaml \
--evolve --resume '/content/yolov9/best (1).pt' \
--cfg models/detect/gelan-c.yaml \
--hyp hyp.scratch-high.yaml
```

Traceback (most recent call last):
  File "/content/yolov9/train.py", line 634, in <module>
    main(opt)
  File "/content/yolov9/train.py", line 604, in main
    hyp[k] = max(hyp[k], v[1])  # lower limit
KeyError: 'obj'
