### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by AndrewHawking** [WongKinYiu/yolov9#157]
Traceback (most recent call last):
  File "D:\yolov9-main\train.py", line 634, in <module>
    main(opt)
  File "D:\yolov9-main\train.py", line 528, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:\yolov9-main\train.py", line 345, in train
    results, maps, _ = validate.run(data_dict,
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\yolo\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\yolov9-main\val.py", line 213, in run
    path, shape = Path(paths[si][0]), shapes[si][0]
                       ~~~~~^^^^
IndexError: list index out of range

how should i fix it ? pls

**Comment by DASDSAJCA** [comment]
hello,I think you should using the moudel named 'yolov9-c.pt' or 'yolov9-e.pt' instead of 'gelan-xx.pt'

**Comment by moralesja560** [comment]
Hi.

What were you doing? Which weight are you using? Which arguments did you run the script with?

I was training my model yesterday and I discovered that I need to use train_dual.py with certain weights, such as gelan-c and yolov9-converted. 

Maybe that is your issue. Try running train_dual.py with your arguments. 

Have a great day.

**Comment by AndrewHawking** [comment]
> hello,I think you should using the moudel named 'yolov9-c.pt' or 'yolov9-e.pt' instead of 'gelan-xx.pt'

thanks

**Comment by AndrewHawking** [comment]
> Hi.
> 
> What were you doing? Which weight are you using? Which arguments did you run the script with?
> 
> I was training my model yesterday and I discovered that I need to use train_dual.py with certain weights, such as gelan-c and yolov9-converted.
> 
> Maybe that is your issue. Try running train_dual.py with your arguments.
> 
> Have a great day.

thanks

**Comment by Capricorn-18** [comment]
running train_dual.py  not error, but the map always zero!!that's why?

**Comment by Tong-Hao741** [comment]
我也遇到了相同的问题，请问您解决了吗？

**Comment by ytl0623** [comment]
Maybe you can try to modify the `copy_paste` parameter in `hyp.scratch-high.yaml` to 0.0.
![image](https://github.com/WongKinYiu/yolov9/assets/55120101/b20077be-a7a0-496f-9e9c-8f29927e4ee8)

I solved the problem by this method.

**Comment by Tong-Hao741** [comment]
thank u，i will try again :)

**Comment by xinlin-xiao** [comment]
[https://github.com/WongKinYiu/yolov9/pull/13/files](url)
its wroked,may you can try.
```](url)
 with dt[2]:
      preds = preds[0][1] if isinstance(preds[0], list) else preds[0]#add
```

**Comment by Tong-Hao741** [comment]
WoW，thank u very much,it work~

**Comment by wenshihao1** [comment]
> [https://github.com/WongKinYiu/yolov9/pull/13/files](url) 它的工作原理，你可以尝试一下。
> 
> ```
>  with dt[2]:
>       preds = preds[0][1] if isinstance(preds[0], list) else preds[0]#add
> ```

Where to add it?

**Comment by xinlin-xiao** [comment]
> > [https://github.com/WongKinYiu/yolov9/pull/13/files](url) 它的工作原理，你可以尝试一下。
> > ```
> >  with dt[2]:
> >       preds = preds[0][1] if isinstance(preds[0], list) else preds[0]#add
> > ```
> 
> Where to add it?

detect.py

**Comment by wenshihao1** [comment]
But I had a problem when I was training.





---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月21日 19:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [WongKinYiu/yolov9] IndexError: list index out of range (Issue #157) |

https://github.com/WongKinYiu/yolov9/pull/13/files 它的工作原理，你可以尝试一下。

 with dt[2]:
      preds = preds[0][1] if isinstance(preds[0], list) else preds[0]#add


Where to add it?

detect.py

**Comment by xinlin-xiao** [comment]
try add it to val.py.



---Original---
From: ***@***.***&gt;
Date: Tue, May 21, 2024 18:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [WongKinYiu/yolov9] IndexError: list index out of range (Issue#157)




 But I had a problem when I was training.
 
 
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2024年05月21日 19:29 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.***&gt;***@***.***&gt; |
 | 主题 | Re: [WongKinYiu/yolov9] IndexError: list index out of range (Issue #157) |
 
 https://github.com/WongKinYiu/yolov9/pull/13/files 它的工作原理，你可以尝试一下。
 
  with dt[2]:
       preds = preds[0][1] if isinstance(preds[0], list) else preds[0]#add
 
 
 Where to add it?
 
 detect.py

**Comment by wenshihao1** [comment]
Didn't find a place to add in val.py



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/21/2024 19:40 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [WongKinYiu/yolov9] IndexError: list index out of range (Issue #157) |

try add it to val.py.



---Original---
From: ***@***.***&gt;
Date: Tue, May 21, 2024 18:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [WongKinYiu/yolov9] IndexError: list index out of range (Issue#157)




But I had a problem when I was training.





---- 回复的原邮件 ----
| 发件人 | ***@***.***&gt; |
| 日期 | 2024年05月21日 19:29 |
| 收件人 | ***@***.***&gt; |
| 抄送至 | ***@***.***&gt;***@***.***&gt; |
| 主题 | Re: [WongKinYiu/yolov9] IndexError: list index out of range (Issue #157) |

https://github.com/WongKinYiu/yolov9/pull/13/files 它的工作原理，你可以尝试一下。

with dt[2]:
preds = preds[0][1] if isinstance(preds[0], list) else preds[0]#add


Where to add it?

detect.py

**Comment by wenshihao1** [comment]
ok, I will try. Thanks.



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/21/2024 19:54 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [WongKinYiu/yolov9] IndexError: list index out of range (Issue #157) |

before nms



---Original---
From: ***@***.***&gt;
Date: Tue, May 21, 2024 18:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [WongKinYiu/yolov9] IndexError: list index out of range (Issue#157)




Didn't find a place to add in val.py



---- Replied Message ----
| From | ***@***.***&gt; |
| Date | 05/21/2024 19:40 |
| To | ***@***.***&gt; |
| Cc | ***@***.***&gt;***@***.***&gt; |
| Subject | Re: [WongKinYiu/yolov9] IndexError: list index out of range (Issue #157) |

try add it to val.py.



---Original---
From: ***@***.***&amp;gt;
Date: Tue, May 21, 2024 18:32 PM
To: ***@***.***&amp;gt;;
Cc: ***@***.******@***.***&amp;gt;;
Subject: Re: [WongKinYiu/yolov9] IndexError: list index out of range (Issue#157)




But I had a problem when I was training.





---- 回复的原邮件 ----
| 发件人 | ***@***.***&amp;gt; |
| 日期 | 2024年05月21日 19:29 |
| 收件人 | ***@***.***&amp;gt; |
| 抄送至 | ***@***.***&amp;gt;***@***.***&amp;gt; |
| 主题 | Re: [WongKinYiu/yolov9] IndexError: list index out of range (Issue #157) |

https://github.com/WongKinYiu/yolov9/pull/13/files 它的工作原理，你可以尝试一下。

with dt[2]:
preds = preds[0][1] if isinstance(preds[0], list) else preds[0]#add


Where to add it?

detect.py

**Comment by tku411770448** [comment]
> Hi.
> 
> What were you doing? Which weight are you using? Which arguments did you run the script with?
> 
> I was training my model yesterday and I discovered that I need to use train_dual.py with certain weights, such as gelan-c and yolov9-converted.
> 
> Maybe that is your issue. Try running train_dual.py with your arguments.
> 
> Have a great day.

@moralesja560 
I'm doing about QAT process, although I use 'yolov9-c7-converted.pt', I keep meeting the issue about ：
  
File "c:\Users\PZJ\Desktop\yolov9\yolov9-main_measure\yolov9-main\val.py", line 213, in run
path, shape = Path(paths[si]), shapes[si][0]
IndexError: list index out of range

Do I need to solve the problem with editing the line 213 in val.py？

**Comment by tku411770448** [comment]
> Hi.
> 
> What were you doing? Which weight are you using? Which arguments did you run the script with?
> 
> I was training my model yesterday and I discovered that I need to use train_dual.py with certain weights, such as gelan-c and yolov9-converted.
> 
> Maybe that is your issue. Try running train_dual.py with your arguments.
> 
> Have a great day.

[https://github.com/levipereira/yolov9-qat?tab=readme-ov-file#quantize-model](url)
This is the link about what I'm working now.
Thanks.
