### ISSUE TITLE
ISSUE: IndexError: list index out of range - while training 'YOLOv9-e' on custom dataset. 

### ISSUE THREAD

**Issue by pranavdurai10** [WongKinYiu/yolov9#161]
I'm trying to train this `yolov9-e.pt` model on a custom dataset. 

Here's my command-line argument: 

`!python train_dual.py \
--batch 64 --epochs 25 --img 640 --device 0 --min-items 0 --close-mosaic 15 --workers 4\
--data /content/yolov9/SkyFusion-YOLOv9/data.yaml \
--weights {HOME}/weights/yolov9-e.pt \
--cfg models/detect/yolov9-e.yaml \
--hyp hyp.scratch-high.yaml`

However, I keep running into this `IndexError: list index out of range`error. 

Here's what the traceback looks like: 

yolov9-e summary: 1475 layers, 69410930 parameters, 69410898 gradients, 244.9 GFLOPs

Transferred 2160/2172 items from {HOME}/weights/yolov9-e.pt
AMP: checks passed ✅
optimizer: SGD(lr=0.01) with parameter groups 356 weight(decay=0.0), 375 weight(decay=0.0005), 373 bias
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
train: Scanning /content/yolov9/SkyFusion-YOLOv9/train/labels.cache... 2094 images, 0 backgrounds, 0 corrupt: 100% 2094/2094 [00:00<?, ?it/s]
val: Scanning /content/yolov9/SkyFusion-YOLOv9/valid/labels.cache... 449 images, 0 backgrounds, 0 corrupt: 100% 449/449 [00:00<?, ?it/s]
Plotting labels to runs/train/exp18/labels.jpg... 
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs/train/exp18
Starting training for 25 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0% 0/33 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/yolov9/train_dual.py", line 644, in <module>
    main(opt)
  File "/content/yolov9/train_dual.py", line 538, in main
    train(opt.hyp, opt, device, callbacks)
  File "/content/yolov9/train_dual.py", line 288, in train
    for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 694, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/yolov9/utils/dataloaders.py", line 656, in __getitem__
    img, labels = self.load_mosaic(index)
  File "/content/yolov9/utils/dataloaders.py", line 791, in load_mosaic
    img4, labels4, segments4 = copy_paste(img4, labels4, segments4, p=self.hyp['copy_paste'])
  File "/content/yolov9/utils/augmentations.py", line 248, in copy_paste
    l, box, s = labels[j], boxes[j], segments[j]
IndexError: list index out of range

Can someone please assist with this?

**Comment by parasmaisalunkhe** [comment]
I am also getting the same error I tried the default dataset that was loaded on the yolov9 google collab which is: 
project = rf.workspace("roboflow-jvuqo").project("football-players-detection-3zvbc")
version = project.version(8)
dataset = version.download("yolov9")
and the code:
!python train_dual.py \ --batch 64 --epochs 25 --img 640 --device 0 --min-items 0 --close-mosaic 15 --workers 4\ --data /content/yolov9/SkyFusion-YOLOv9/data.yaml \ --weights {HOME}/weights/yolov9-e.pt \ --cfg models/detect/yolov9-e.yaml \ --hyp hyp.scratch-high.yaml
works perfectly but when I use this dataset:
project = rf.workspace("zr-testing").project("zrv2")
version = project.version(32)
dataset = version.download("yolov9")
I get the Same error as @pranavdurai10

**Comment by Kitagawayyds** [comment]
i have the same problem :(

**Comment by pranavdurai10** [comment]
@Kitagawayyds @parasmaisalunkhe - Please go ahead with Ultralytics implementation of YOLOv9. 

Link: https://docs.ultralytics.com/models/yolov9/

**Comment by Kitagawayyds** [comment]
> @Kitagawayyds @parasmaisalunkhe - Please go ahead with Ultralytics implementation of YOLOv9.
> 
> Link: https://docs.ultralytics.com/models/yolov9/

is this problem solved? (in Ultralytics)

**Comment by pranavdurai10** [comment]
@Kitagawayyds - Yes, I'm able to train both YOLOv9-C and E models on a custom dataset.

**Comment by parasmaisalunkhe** [comment]
I solved my problem basically in roboflow I added Resize: Stretch to 640x640 to my Preproccesing of my dataset which works with the: !python train_dual.py \ --batch 64 --epochs 25 --img 640 --device 0 --min-items 0 --close-mosaic 15 --workers 4\ --data /content/yolov9/SkyFusion-YOLOv9/data.yaml \ --weights {HOME}/weights/yolov9-e.pt \ --cfg models/detect/yolov9-e.yaml \ --hyp hyp.scratch-high.yaml and I thinik the img flag represents 640 by 640 so it works now

**Comment by pranavdurai10** [comment]
@parasmaisalunkhe - in that way, my dataset already had 640x640 images. 

It still didn't work.

**Comment by parasmaisalunkhe** [comment]
thanks the ultralytics documentation works now

**Comment by PranethReddy** [comment]
> thanks the ultralytics documentation works now

bro.. could you tell me how did you resolved that issue on 
IndexError: list index out of range

**Comment by Narenk9** [comment]
same issue here
I am using this dataset which already has, Resize: Stretch to 640x640
rf = Roboflow(api_key="")
project = rf.workspace("university-of-southeastern-philippines-cnl9c").project("license-plate-detection-merged-projects")
version = project.version(3)
dataset = version.download("yolov9")

!python train.py \
--batch 16 --epochs 25 --img 640 --device 0 --min-items 0 --close-mosaic 15 \
--data {dataset.location}/data.yaml \
--weights {HOME}/weights/yolov9-c.pt \
--cfg models/detect/yolov9.yaml \
--hyp hyp.scratch-high.yaml
please check the error

**Comment by IsraaSaede** [comment]
@parasmaisalunkhe, could you kindly explain how you resized the dataset? I'm not familiar with how to do it using the YAML format from Roboflow.

**Comment by googzzgsee** [comment]
modify hyp.scratch-high.yaml 
old  copy_paste: 0.3  # segment copy-paste (probability)
new copy_paste: 0.1 or 0.0

**Comment by abdulkadrtr** [comment]
@googzzgsee not working

**Comment by ytl0623** [comment]
Modify the `copy_paste` parameter in `hyp.scratch-high.yaml` to 0.0 helps me solved the problem.
![image](https://github.com/WongKinYiu/yolov9/assets/55120101/b20077be-a7a0-496f-9e9c-8f29927e4ee8)

**Comment by parasmaisalunkhe** [comment]
tysm @ytl0623 it works for me

**Comment by Jacko760** [comment]
> Modify the `copy_paste` parameter in `hyp.scratch-high.yaml` to 0.0 helped me solve the problem. ![image](https://private-user-images.githubusercontent.com/55120101/315916074-b20077be-a7a0-496f-9e9c-8f29927e4ee8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODI2NjQsIm5iZiI6MTcxMzI4MjM2NCwicGF0aCI6Ii81NTEyMDEwMS8zMTU5MTYwNzQtYjIwMDc3YmUtYTdhMC00OTZmLTllOWMtOGYyOTkyN2U0ZWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1NDYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OTUzZDc5YzExMTgwYjU4YzY4YzEzODdiYjk3MmFhMTRiZTdhOTEwYjUxNDYwZWFiOWY5YmI4ZmE5ZTVmYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2xVdZ4SKdMcxEjqiZNa4WrIa4d2WCv_50T5d3NCxyXA)

its working but can you explain the intution behind this ? why is that so ?

**Comment by hxq11** [comment]
Starting training for 5 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        0/4      1.85G      2.066      3.152      2.312          4        640:   0%|          | 0/303 00:02WARNING ⚠️ TensorBoard graph visualization failure Only tensors, lists, tuples of tensors, or dictionary of tensors can be output from traced functions
        0/4      2.89G      2.106      4.011      2.589          1        640: 100%|██████████| 303/303 04:18
                 Class     Images  Instances          P          R      mAP50   mAP50-95:   0%|          | 0/11 00:00si: 0, len(paths): 2, len(shapes): 2
si: 1, len(paths): 2, len(shapes): 2
                 Class     Images  Instances          P          R      mAP50   mAP50-95:   0%|          | 0/11 00:00
Traceback (most recent call last):
  File "train_dual.py", line 644, in <module>
    main(opt)
  File "train_dual.py", line 538, in main
    train(opt.hyp, opt, device, callbacks)
  File "train_dual.py", line 356, in train
    results, maps, _ = validate.run(data_dict,
  File "/data/hxq/anaconda3/envs/YOLOv9/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/hxq/work/Comparison-model/yolov9/val_dual.py", line 228, in run
    path, shape = Path(paths[si]), shapes[si][0]
IndexError: list index out of range
还是无法解决

**Comment by Varun3713-creator** [comment]
> Modify the `copy_paste` parameter in `hyp.scratch-high.yaml` to 0.0 helped me solve the problem. ![image](https://private-user-images.githubusercontent.com/55120101/315916074-b20077be-a7a0-496f-9e9c-8f29927e4ee8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzQxNTgsIm5iZiI6MTcxOTU3Mzg1OCwicGF0aCI6Ii81NTEyMDEwMS8zMTU5MTYwNzQtYjIwMDc3YmUtYTdhMC00OTZmLTllOWMtOGYyOTkyN2U0ZWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDExMjQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MmY2M2M1OTljNjEzZDRkZDk4N2IyYmNkY2U3OGRhMDVkMDE0ODAxZmJiOTg2MTcwOGMzYmNlNGMwOThhOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pod3U1gVzK6tSE67lLOMhdgR83Ysmsp7rowaU-hA07I)

it is working..thank you

**Comment by 4-alok** [comment]
> hyp.scratch-high.yam

where is this file

**Comment by nowjean** [comment]
> Modify the `copy_paste` parameter in `hyp.scratch-high.yaml` to 0.0 helped me solve the problem. ![image](https://private-user-images.githubusercontent.com/55120101/315916074-b20077be-a7a0-496f-9e9c-8f29927e4ee8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4MzU0MjMsIm5iZiI6MTczNjgzNTEyMywicGF0aCI6Ii81NTEyMDEwMS8zMTU5MTYwNzQtYjIwMDc3YmUtYTdhMC00OTZmLTllOWMtOGYyOTkyN2U0ZWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE0VDA2MTIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNDAzODVhYjE0MWIzNzFlZmJhZDNkMjJhYTU1NDJkYzRkNzNmOTNkYjI5M2QxZjAyNTkzZTVkOTk5ZWIwM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rUVh9HqE7mYIc-Ihv3RsVokvTUt2XcDRWPus_rxI8AI)

it is working! but i don't know why..

**Comment by PranethReddy** [comment]
thank you for that solution
