### ISSUE TITLE
Error about detect.py

### ISSUE THREAD

**Issue by jayer95** [WongKinYiu/yolov9#162]
When I execute the command to test "detect.py",

python detect.py \
    --source test.mp4 \
    --weights yolov9-e.pt \
    --imgsz 640 \
    --conf-thres 0.25 \
    --iou-thres 0.1
    
I encountered the following error:

Traceback (most recent call last):
  File "/home/gvsai/yolov9/detect.py", line 231, in <module>
    main(opt)
  File "/home/gvsai/yolov9/detect.py", line 226, in main
    run(**vars(opt))
  File "/home/gvsai/anaconda3/envs/yolov5/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gvsai/yolov9/detect.py", line 102, in run
    pred = non_max_suppression(pred, conf_thres, iou_thres, classes, agnostic_nms, max_det=max_det)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gvsai/yolov9/utils/general.py", line 905, in non_max_suppression
    device = prediction.device
             ^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'device'

The following line needs to be changed:
https://github.com/WongKinYiu/yolov9/blob/9660d127cf5a4f8d51d19b09ba299f98a0672ca7/detect.py#L98

to:

`pred, _ = model(im, augment=augment, visualize=visualize)
`

Then "detect.py" can be executed normally!

**Comment by mkrupczak3** [comment]
#11

**Comment by jayer95** [comment]
@mkrupczak3 thanks!!
