### ISSUE TITLE
Can use custom datasets of yolov7 to train with yolov9?

### ISSUE THREAD

**Issue by xjohnxjohn** [WongKinYiu/yolov9#212]

**Comment by WongKinYiu** [comment]
Yes, just you may need delete .cache files and re-generate them.

**Comment by xjohnxjohn** [comment]
> Yes, just you may need delete .cache files and re-generate them.
Hi, Thank for reply. I found error 
"IndexError: Caught IndexError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/YOLOV7_SOURCE_310/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/YOLOV7_SOURCE_310/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/YOLOV7_SOURCE_310/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/john/yolov9-steel-rod/utils/dataloaders.py", line 656, in __getitem__
    img, labels = self.load_mosaic(index)
  File "/home/john/yolov9-steel-rod/utils/dataloaders.py", line 791, in load_mosaic
    img4, labels4, segments4 = copy_paste(img4, labels4, segments4, p=self.hyp['copy_paste'])
  File "/home/john/yolov9-steel-rod/utils/augmentations.py", line 248, in copy_paste
    l, box, s = labels[j], boxes[j], segments[j]
IndexError: list index out of range
"

**Comment by WongKinYiu** [comment]
If you do not provide polygon annotation, you must turn off copy paste augmentation in hyp.yaml.
