### ISSUE TITLE
when i set datasets yaml in single class

### ISSUE THREAD

**Issue by dabaonidetou** [WongKinYiu/yolov9#218]
train: /usr/src/yolov9/data/datasets/images/train
val: /usr/src/yolov9/data/datasets/images/val
test: /usr/src/yolov9/data/datasets/images/test

nc : 1
names: [ 'helmet']

Traceback (most recent call last):
  File "/usr/src/yolov9/train_dual.py", line 644, in <module>
    main(opt)
  File "/usr/src/yolov9/train_dual.py", line 538, in main
    train(opt.hyp, opt, device, callbacks)
  File "/usr/src/yolov9/train_dual.py", line 207, in train
    assert mlc < nc, f'Label class {mlc} exceeds nc={nc} in {data}. Possible class labels are 0-{nc - 1}'
AssertionError: Label class 1 exceeds nc=1 in /usr/src/yolov9/data/helmet.yaml. Possible class labels are 0-0

**Comment by Visiblemiracle** [comment]
set nc 1 in models/detect/ .yaml file
