### ISSUE TITLE
inference with yolov9-c-converted.pt

### ISSUE THREAD

**Issue by AndreSchakkal** [WongKinYiu/yolov9#227]
Hello,

I'm trying to do inference with the `yolov9-c-converted.pt` weights using the command given in the ReadMe file:
`python detect.py --source './data/images/horses.jpg' --img 640 --device 0 --weights yolov9-c-converted.pt --name yolov9_c_c_640_detect`

However, I get the following error:
detect: weights=['yolov9-c-converted.pt'], source='./data/images/horses.jpg', data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=0, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=yolov9_c_c_640_detect, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLO  v0.1-60-g4cf2226 Python-3.11.8 torch-2.2.1+cu121 CUDA:0 (NVIDIA RTX A2000 8GB Laptop GPU, 8192MiB)

Traceback (most recent call last):
  File "C:\Users\aschakkal\Desktop\yolov9\detect.py", line 231, in <module>
    main(opt)
  File "C:\Users\aschakkal\Desktop\yolov9\detect.py", line 226, in main
    run(**vars(opt))
  File "C:\Users\aschakkal\Desktop\venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aschakkal\Desktop\yolov9\detect.py", line 68, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aschakkal\Desktop\yolov9\models\common.py", line 684, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aschakkal\Desktop\yolov9\models\experimental.py", line 243, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aschakkal\Desktop\venv\Lib\site-packages\torch\serialization.py", line 1026, in load
    return _load(opened_zipfile,
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aschakkal\Desktop\venv\Lib\site-packages\torch\serialization.py", line 1438, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "C:\Users\aschakkal\Desktop\venv\Lib\site-packages\torch\serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'yolov9'

Thank you for your help

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolov9/releases/download/v0.1/yolov9-c-converted.pt

You need download the weights file first.

**Comment by AndreSchakkal** [comment]
Thank you!
