### ISSUE TITLE
detect.py  cannot run on windows

### ISSUE THREAD

**Issue by sweet-de-way** [WongKinYiu/yolov9#234]
Fusing layers...
gelan-c summary: 387 layers, 25230172 parameters, 0 gradients, 101.8 GFLOPs
Traceback (most recent call last):
  File "D:\temp\yolov9\detect.py", line 231, in <module>
    main(opt)
  File "D:\temp\yolov9\detect.py", line 226, in main
    run(**vars(opt))
  File "C:\Users\ltsswpp\.conda\envs\yolo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\temp\yolov9\detect.py", line 155, in run
    cv2.waitKey(1)  # 1 millisecond
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1338: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvWaitKey'

I had to delete the line154 and line155 in detect.py to run.

**Comment by sweet-de-way** [comment]
https://github.com/opencv/opencv-python/issues/18
