### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by AniketKumar10** [WongKinYiu/yolov9#265]
I don't know what's the issue here I can't really get it 

Traceback (most recent call last):
  File "/content/yolov9/train.py", line 634, in <module>
    main(opt)
  File "/content/yolov9/train.py", line 528, in main
    train(opt.hyp, opt, device, callbacks)
  File "/content/yolov9/train.py", line 108, in train
    ckpt = torch.load(weights, map_location='cpu')  # load checkpoint to CPU to avoid CUDA memory leak
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

This it the detailed error that I am getting.
Can Someone help me understand it.

**Comment by AniketKumar10** [comment]
mb it was just a typo :)
