### ISSUE TITLE
error segment custum

### ISSUE THREAD

**Issue by POVTUASTHOV** [WongKinYiu/yolov9#270]
!python /media/tat/Learn/YOLO/yolov9/segment/predict.py --source '/media/tat/Learn/bat_thuong_duong_day_dien/out_label/chx_gan/z3973512489978_d2a3e20e916faa20543d0d99758ae2a8_jpg.rf.992f2eb2586e888d8c55cb0aabdf3d0b.jpg' --img 640 --device 0 --weights '/media/tat/Learn/bat_thuong_duong_day_dien/out_label/best.pt' --name gelan-c-seg

error
Fusing layers... 
gelan-c-seg summary: 414 layers, 27369838 parameters, 0 gradients, 144.3 GFLOPs
Traceback (most recent call last):
  File "/media/tat/Learn/YOLO/yolov9/segment/predict.py", line 246, in <module>
    main(opt)
  File "/media/tat/Learn/YOLO/yolov9/segment/predict.py", line 241, in main
    run(**vars(opt))
  File "/home/tat/anaconda3/envs/django/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/media/tat/Learn/YOLO/yolov9/segment/predict.py", line 126, in run
    masks = process_mask(proto[i], det[:, 6:], det[:, :4], im.shape[2:], upsample=True)  # HWC
  File "/media/tat/Learn/YOLO/yolov9/utils/segment/general.py", line 54, in process_mask
    c, mh, mw = protos.shape  # CHW
AttributeError: 'list' object has no attribute 'shape'

**Comment by gengdd** [comment]
```python
masks = process_mask(proto[i], det[:, 6:], det[:, :4], im.shape[2:], upsample=True) # HWC
# Just correct it as follows
masks = process_mask(proto[-1][i], det[:, 6:], det[:, :4], im.shape[2:], upsample=True) # HWC
```
