### ISSUE TITLE
assert len(files), f'File not found: {file}'  # assert file was found AssertionErr

### ISSUE THREAD

**Issue by pascal-maker** [WongKinYiu/yolov9#271]
Following [SkalskiP]  tutorial How to Train YOLOv9 on a Custom Dataset i try to runntrain.py  using the extact location where data.yaml is found. I receive the  following error yolov9 % python train.py \
--batch 16 --epochs 25 --img 640 --device cpu --min-items 0 --close-mosaic 15 \
--data yolov9/{HOME}/weights/football-players-detection.v8i.yolov9/data.yaml \
--weights {HOME}/weights/gelan-c.pt \
--cfg models/detect/gelan-c.yaml \
--hyp hyp.scratch-high.yaml

train: weights={HOME}/weights/gelan-c.pt, cfg=models/detect/gelan-c.yaml, data=yolov9/{HOME}/weights/football-players-detection.v8i.yolov9/data.yaml, hyp=hyp.scratch-high.yaml, epochs=25, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=cpu, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, flat_cos_lr=False, fixed_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, min_items=0, close_mosaic=15, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
Traceback (most recent call last):
  File "/Users/pascal/python-opencv/yolov9/train.py", line 634, in <module>
    main(opt)
  File "/Users/pascal/python-opencv/yolov9/train.py", line 503, in main
    check_file(opt.data), check_yaml(opt.cfg), check_yaml(opt.hyp), str(opt.weights), str(opt.project)  # checks
  File "/Users/pascal/python-opencv/yolov9/utils/general.py", line 478, in check_file
    assert len(files), f'File not found: {file}'  # assert file was found
AssertionErr

**Comment by Ska-chev** [comment]
Similar error like this when training yolov5：
 Traceback (most recent call last):
  File "train.py", line 620, in <module>
    main(opt)
  File "train.py", line 497, in main
    check_file(opt.data), check_yaml(opt.cfg), check_yaml(opt.hyp), str(opt.weights), str(opt.project)  # checks
  File "D:\APyCharmresources\yolo\yolov5_6.0\yolov5_6.0\utils\general.py", line 326, in check_file
    assert len(files), f'File not found: {file}'  # assert file was found
AssertionError: File not found: data/myvoc.yaml
Solving by renaming the file ”ROOT /data/My_Voc“ as ”myvoc.yaml“
