### ISSUE TITLE
RuntimeError: shape '[82, 82, -1]' is invalid for input of size 524800

### ISSUE THREAD

**Issue by cowardless** [WongKinYiu/yolov9#282]
I use the command "python train.py --workers 8 --device 0 --batch 12 --data detectV1-3/data.yaml --img 640 --cfg models/detect/gelan.yaml --weights '' --name gelan-c --hyp hyp.scratch-high.yaml --min-items 0 --epochs 500 --close-mosaic 15" to train my own dataset. And then I got an error message "
Traceback (most recent call last):
  File "train.py", line 634, in <module>
    main(opt)
  File "train.py", line 528, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 304, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/media/amax/data/syq/yolov5detect/yolov9-main/utils/loss_tal.py", line 168, in __call__
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
  File "/media/amax/data/syq/yolov5detect/yolov9-main/utils/loss_tal.py", line 168, in <listcomp>
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
RuntimeError: shape '[82, 82, -1]' is invalid for input of size 524800
"
I just change the numbers of classes to adapt to my own datasets.

**Comment by Youho99** [comment]
Use gelan-c or gelan-e instead of "gelan" config file

**Comment by 13971182511** [comment]
How to solve it? I have the same problem.

**Comment by Zhuqing11223** [comment]
How to solve it ？
