### ISSUE TITLE
如何训练模型 yolov7-af.yaml ？

### ISSUE THREAD

**Issue by wgqhandsome** [WongKinYiu/yolov9#396]

**Comment by wgqhandsome** [comment]
Starting training for 1 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/55 00:01
Traceback (most recent call last):
  File "./code-object-detection/train.py", line 636, in <module>
    main(opt)
  File "./code-object-detection/train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "./code-object-detection/train.py", line 304, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/autodl-fs/data/ml-object-detection/code-object-detection/utils/loss_tal.py", line 168, in __call__
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
  File "/autodl-fs/data/ml-object-detection/code-object-detection/utils/loss_tal.py", line 168, in <listcomp>
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
RuntimeError: shape '[65, 65, -1]' is invalid for input of size 416000
{"code":"Success","data":null,"msg":""}
