### ISSUE TITLE
I m tryin t add an attention layer but it seems my tensors aren't matching even after making necessary changes can you please help me to reolve it

### ISSUE THREAD

**Issue by p-dot-max** [WongKinYiu/yolov9#400]
Traceback (most recent call last):
  File "/content/drive/MyDrive/Yolo/yolov9_atten/yolov9_attention_codebase/train.py", line 633, in <module>
    main(opt)
  File "/content/drive/MyDrive/Yolo/yolov9_atten/yolov9_attention_codebase/train.py", line 527, in main
    train(opt.hyp, opt, device, callbacks)
  File "/content/drive/MyDrive/Yolo/yolov9_atten/yolov9_attention_codebase/train.py", line 115, in train
    model = Model(cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/content/drive/MyDrive/Yolo/yolov9_atten/yolov9_attention_codebase/models/yolo.py", line 619, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
  File "/content/drive/MyDrive/Yolo/yolov9_atten/yolov9_attention_codebase/models/yolo.py", line 618, in <lambda>
    forward = lambda x: self.forward(x)[0][0] if isinstance(m, (DualDSegment)) else self.forward(x)[0]
  File "/content/drive/MyDrive/Yolo/yolov9_atten/yolov9_attention_codebase/models/yolo.py", line 633, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/content/drive/MyDrive/Yolo/yolov9_atten/yolov9_attention_codebase/models/yolo.py", line 533, in _forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/Yolo/yolov9_atten/yolov9_attention_codebase/models/common.py", line 742, in forward
    res = [F.interpolate(x[self.idx[i]], size=target_size, mode='nearest') for i, x in enumerate(xs[:-1])]
  File "/content/drive/MyDrive/Yolo/yolov9_atten/yolov9_attention_codebase/models/common.py", line 742, in <listcomp>
    res = [F.interpolate(x[self.idx[i]], size=target_size, mode='nearest') for i, x in enumerate(xs[:-1])]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 3934, in interpolate
    raise ValueError(
ValueError: Input and output must have the same number of spatial dimensions, but got input with spatial dimensions of [8] and output size of torch.Size([32, 32]). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.

**Comment by p-dot-max** [comment]
how do i align input and output correctly
