### ISSUE TITLE
AttributeError: 'list' object has no attribute 'view'

### ISSUE THREAD

**Issue by Teameviral** [WongKinYiu/yolov9#413]
Traceback (most recent call last):
  File "/content/yolov9/train.py", line 634, in <module>
    main(opt)
  File "/content/yolov9/train.py", line 528, in main
    train(opt.hyp, opt, device, callbacks)
  File "/content/yolov9/train.py", line 304, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/content/yolov9/utils/loss_tal.py", line 168, in __call__
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
  File "/content/yolov9/utils/loss_tal.py", line 168, in <listcomp>
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
AttributeError: 'list' object has no attribute 'view'

**Comment by Mecanight** [comment]
I also have the same problem!

**Comment by KoniHD** [comment]
Doing the work of @Youho99 here :)
Your issue looks the same as #315  or #302.
Probably you used a Yolov9 model with train.py. However, you need to use train_dual.py with a yolov9 model as train.py is only for Gelan models. Meaning you can either use a Gelan model with train.py as @Mecanight mentioned or use train_dual.py with the yolov9 model. (See #1)

**Comment by Techydeveloper12** [comment]
Traceback (most recent call last):
  File "/content/yolov9/train.py", line 634, in <module>
    main(opt)
  File "/content/yolov9/train.py", line 528, in main
    train(opt.hyp, opt, device, callbacks)
  File "/content/yolov9/train.py", line 277, in train
    for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 705, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/yolov9/utils/dataloaders.py", line 656, in __getitem__
    img, labels = self.load_mosaic(index)
  File "/content/yolov9/utils/dataloaders.py", line 791, in load_mosaic
    img4, labels4, segments4 = copy_paste(img4, labels4, segments4, p=self.hyp['copy_paste'])
  File "/content/yolov9/utils/augmentations.py", line 248, in copy_paste
    l, box, s = labels[j], boxes[j], segments[j]
IndexError: list index out of range

**Comment by aliwaqas333** [comment]
> Doing the work of @Youho99 here :) Your issue looks the same as #315 or #302. Probably you used a Yolov9 model with train.py. However, you need to use train_dual.py with a yolov9 model as train.py is only for Gelan models. Meaning you can either use a Gelan model with train.py as @Mecanight mentioned or use train_dual.py with the yolov9 model. (See #1)

Why isnt this mentioned anywhere in the docs? Are we supposed to know this? Where is more such info shared?

**Comment by Vaibhav-solum** [comment]
The error at line 168 in utils/loss_tal.py appears to be caused by the output of feats being a nested list rather than a list of tensors. In the current implementation, the code assumes each element in feats is a tensor and directly calls .view() on xi. However, since feats contains two lists, xi becomes a list object, which results in AttributeError: 'list' object has no attribute 'view'. 

Solution: Adding feats = feats[0] just before line 168 resolves the issue by ensuring that feats is a list of tensors before applying the .view() operation. It may also be worth adding a structural check to handle such cases more robustly.

<img width="838" height="72" alt="Image" src="https://github.com/user-attachments/assets/e52d2736-ee84-4f0b-ba4e-1c4c225d487a" />
