### ISSUE TITLE
segment/train_dual.py  val loss is all zero.

### ISSUE THREAD

**Issue by zhaochenmeng** [WongKinYiu/yolov9#417]
Trained with segment/train_dual.py and found that val/box_loss was all zeros
![results](https://github.com/WongKinYiu/yolov9/assets/126865622/6da25ef4-ec6c-4902-a70b-c178e5732a13)
Error after uncommenting line 246 in val_dual：Traceback (most recent call last):
  File "E:\AI\yolov9\segment\train_dual.py", line 648, in <module>
    main(opt)
  File "E:\AI\yolov9\segment\train_dual.py", line 544, in main
    train(opt.hyp, opt, device, callbacks)
  File "E:\AI\yolov9\segment\train_dual.py", line 347, in train
    results, maps, _ = validate.run(data_dict,
  File "D:\Deeplearning\anaconda3\envs\yolov5\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\yolov9\segment\val_dual.py", line 248, in run
    loss += compute_loss(train_out, targets, masks)[1]  # box, obj, cls
  File "E:\AI\yolov9\utils\segment\loss_tal_dual.py", line 183, in __call__
    batch_size,_,  mask_h, mask_w = proto.shape
ValueError: not enough values to unpack (expected 4, got 3)

**Comment by jdiaz97** [comment]
multi-gpu or single-gpu?

**Comment by zhaochenmeng** [comment]
> single-gpu

**Comment by Mahonehan** [comment]
Do you solve the problem?

**Comment by zhaochenmeng** [comment]
> 你解决了问题吗？

Not yet

**Comment by shahriarahmadf** [comment]
Currently the val/box_loss are kept zero for the yolov9 code train_dual.py file. Don't know why though
Either we have to find out to how get around or wait for the update.

**Comment by babakbch** [comment]
any solution to this problem so far?

**Comment by louis0831** [comment]
Is the problem solved?
