### ISSUE TITLE
AttributeError: 'list' object has no attribute 'view'

### ISSUE THREAD

**Issue by Shoaibabidi** [WongKinYiu/yolov9#420]
I was trying to train a model on my custom dataset when this error occurred. 

Traceback (most recent call last):
  File "/content/yolov9/train.py", line 634, in <module>
    main(opt)
  File "/content/yolov9/train.py", line 528, in main
    train(opt.hyp, opt, device, callbacks)
  File "/content/yolov9/train.py", line 304, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/content/yolov9/utils/loss_tal.py", line 168, in __call__
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
  File "/content/yolov9/utils/loss_tal.py", line 168, in <listcomp>
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
AttributeError: 'list' object has no attribute 'view'

**Comment by luccahuguet** [comment]
Thanks @KoniHD, solved my problem
