### ISSUE TITLE
Yolov9 Train AttributeError: 'FreeTypeFont' object has no attribute 'getsize and nan values

### ISSUE THREAD

**Issue by Hanysabeh** [WongKinYiu/yolov9#437]
i'm using graphics card Nvidia GTX 16 Series  4 GB and i can start training the model on CPU normally but it's very slow so i'm trying to train the model on GPU but i receive the following error 

box_loss   cls_loss   dfl_loss with nan values    

![Screenshot from 2024-05-13 12-39-33](https://github.com/WongKinYiu/yolov9/assets/9498740/161d0f7c-4da3-4284-b0dd-8ec20988fbd7)
Also 
Traceback (most recent call last):
  File "/home/hss/anaconda3/envs/GPU2/lib/python3.12/threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "/home/hss/anaconda3/envs/GPU2/lib/python3.12/threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hss/Desktop/Project/y1/yolov9/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)
  File "/home/hss/Desktop/Project/y1/yolov9/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height
           ^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

**Comment by helpbird** [comment]
pip install Pillow==9.0.1

**Comment by guillermo-gabrielli-fer** [comment]
Try pip install "Pillow<10"

**Comment by WongKinYiu** [comment]
`pip install Pillow==9.5.0`
