### ISSUE TITLE
Attention mechanism 

### ISSUE THREAD

**Issue by p-dot-max** [WongKinYiu/yolov9#454]

**Comment by p-dot-max** [comment]
# up-concat merge
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 7], 1, Concat, [1]],  # cat backbone P4

   # elan-2 block
   [-1, 1, RepNCSPELAN4, [512, 512, 256, 1]],  # 13
   [-1, 1, ResBlock_CBAM, [ 512 ]],

**Comment by p-dot-max** [comment]
@WongKinYiu

**Comment by p-dot-max** [comment]
Heres the update so i modified the cbfuse 


`
class CBFuse(nn.Module):
    def __init__(self, idx):
        super(CBFuse, self).__init__()
        self.idx = idx

    def forward(self, xs):
        tensor_shapes = [x.shape for x in xs if isinstance(x, torch.Tensor)]
        max_height = max([shape[2] for shape in tensor_shapes]) if tensor_shapes else 0
        max_width = max([shape[3] for shape in tensor_shapes]) if tensor_shapes else 0
        max_channels = max([shape[1] for shape in tensor_shapes]) if tensor_shapes else 0
        target_size = (max_height, max_width)

        res = []
        for i, x in enumerate(xs[:-1]):
            if isinstance(x, torch.Tensor):
                selected_feature = x[self.idx[i]] if isinstance(self.idx[i], (list, tuple)) else x

                if len(selected_feature.shape) == 1:  # if feature is 1-D
                    selected_feature = selected_feature.unsqueeze(-1).unsqueeze(-1)  # add spatial dimensions
                elif len(selected_feature.shape) == 2:  # if feature is 2-D
                    selected_feature = selected_feature.unsqueeze(-1)  # add spatial dimensions

                interpolated_feature = F.interpolate(selected_feature, size=target_size, mode='nearest')
                
                if interpolated_feature.shape[1] < max_channels:
                    pad_channels = max_channels - interpolated_feature.shape[1]
                    padded_feature = F.pad(interpolated_feature, (0, 0, 0, 0, 0, pad_channels))
                else:
                    padded_feature = interpolated_feature

                res.append(padded_feature)

        if isinstance(xs[-1], tuple):
            xs[-1] = torch.stack(xs[-1], dim=0)  # convert tuple to tensor

        if xs[-1].shape[1] < max_channels:
            pad_channels = max_channels - xs[-1].shape[1]
            xs[-1] = F.pad(xs[-1], (0, 0, 0, 0, 0, pad_channels))

        out = torch.sum(torch.stack(res + [xs[-1]]), dim=0)
        return out

`

with error 


out shape: torch.Size([1, 512, 16, 16]), residual shape: torch.Size([1, 512, 16, 16])
Traceback (most recent call last):
  File "C:\Users\..\Music\yolov9_attention\yolov9\train.py", line 634, in <module>
    main(opt)
  File "C:\Users\..\Music\yolov9_attention\yolov9\train.py", line 528, in main
    train(opt.hyp, opt, device, callbacks)
  File "C:\Users\..\Music\yolov9_attention\yolov9\train.py", line 116, in train
    model = Model(cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\..\Music\yolov9_attention\yolov9\models\yolo.py", line 620, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\..\Music\yolov9_attention\yolov9\models\yolo.py", line 619, in <lambda>
    forward = lambda x: self.forward(x)[0][0] if isinstance(m, (DualDSegment)) else self.forward(x)[0]
                                                                                    ^^^^^^^^^^^^^^^
  File "C:\Users\..\Music\yolov9_attention\yolov9\models\yolo.py", line 634, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\..\Music\yolov9_attention\yolov9\models\yolo.py", line 533, in _forward_once
    x = m(x)  # run
        ^^^^
  File "C:\Users\..\Music\yolov9_attention\prac\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\..\Music\yolov9_attention\prac\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\..\Music\yolov9_attention\yolov9\models\common.py", line 700, in forward
    y = list(self.cv1(x).chunk(2, 1))
             ^^^^^^^^^^^
  File "C:\Users\..\Music\yolov9_attention\prac\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\..\Music\yolov9_attention\prac\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\..\Music\yolov9_attention\yolov9\models\common.py", line 54, in forward
    return self.act(self.bn(self.conv(x)))
                            ^^^^^^^^^^^^
  File "C:\Users\..\Music\yolov9_attention\prac\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\..\Music\yolov9_attention\prac\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\..\Music\yolov9_attention\prac\Lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\..\Music\yolov9_attention\prac\Lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Given groups=1, weight of size [256, 256, 1, 1], expected input[1, 512, 32, 32] to have 256 channels, but got 512 channels instead

**Comment by Umsh** [comment]
@p-dot-max any information to this in adding attention mechanism?
