### ISSUE TITLE
3090正常运行，换成4090 读取数据的时候就开始报超时错误！

### ISSUE THREAD

**Issue by HappyStupidChild** [WongKinYiu/yolov9#458]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\pc\.conda\envs\yv9\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\pc\.conda\envs\yv9\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\pc\.conda\envs\yv9\lib\site-packages\albumentations\__init__.py", line 11, in <module>
    check_for_updates()
  File "C:\Users\pc\.conda\envs\yv9\lib\site-packages\albumentations\check_version.py", line 23, in check_for_updates
    data = response.read()
  File "C:\Users\pc\.conda\envs\yv9\lib\http\client.py", line 472, in read
    s = self._safe_read(self.length)
  File "C:\Users\pc\.conda\envs\yv9\lib\http\client.py", line 613, in _safe_read
    data = self.fp.read(amt)
  File "C:\Users\pc\.conda\envs\yv9\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\pc\.conda\envs\yv9\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\pc\.conda\envs\yv9\lib\ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

**Comment by itachi1232gg** [comment]
查查你机器有网络没

**Comment by HappyStupidChild** [comment]
> 查查你机器有网络没

网络正常
