### ISSUE TITLE
about multi-level reversible auxiliary branch

### ISSUE THREAD

**Issue by Godk02** [WongKinYiu/yolov9#469]
In the auxiliary branch, I only want to keep the A3 detection header, the remaining auxiliary branches are all deleted, will report an error, I would like to ask, this idea can be achieved?
![image](https://github.com/WongKinYiu/yolov9/assets/145435036/29241433-630d-4afe-8761-95017e4fbc09)
The rest of the code remains unchanged and the code reports the error as follows：
`Traceback (most recent call last):
  File "train_dual.py", line 644, in <module>
    main(opt)
  File "train_dual.py", line 538, in main
    train(opt.hyp, opt, device, callbacks)
  File "train_dual.py", line 315, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/home/qk/project/yolov9-main/utils/loss_tal_dual.py", line 197, in __call__
    pred_bboxes2 = self.bbox_decode(anchor_points, pred_distri2)  # xyxy, (b, h*w, 4)
  File "/home/qk/project/yolov9-main/utils/loss_tal_dual.py", line 168, in bbox_decode
    return dist2bbox(pred_dist, anchor_points, xywh=False)
  File "/home/qk/project/yolov9-main/utils/tal/anchor_generator.py", line 26, in dist2bbox
    x1y1 = anchor_points - lt
RuntimeError: The size of tensor a (12800) must match the size of tensor b (2000) at non-singleton dimension 1`

**Comment by WongKinYiu** [comment]
The code only support pair main branch and auxiliary branch.
For example, main branch's outputs are 16, 19, 22 which strides are 8(P3), 16(P4), 32(P5).
Your auxiliary should has also 3 outputs which have stride 8, 16, 32, respectively.
In your case,  the code will take {31, 16} as auxiliary outputs, and {19, 22} as main outputs.

**Comment by Godk02** [comment]
> The code only support pair main branch and auxiliary branch. For example, main branch's outputs are 16, 19, 22 which strides are 8(P3), 16(P4), 32(P5). Your auxiliary should has also 3 outputs which have stride 8, 16, 32, respectively. In your case, the code will take {31, 16} as auxiliary outputs, and {19, 22} as main outputs.

I see. Thanks for your contribution.
