### ISSUE TITLE
Converting to TFLite model fails

### ISSUE THREAD

**Issue by aayushb-95** [WongKinYiu/yolov9#513]
Hi,
I am trying to convert the Pytorch model to TFLite model. However I am getting the following error
```
TensorFlow SavedModel: export failure ❌ 13.7s: cannot import name 'C3' from 'models.common' 

TensorFlow Lite: starting export with tensorflow 2.16.1...
TensorFlow Lite: export failure ❌ 0.0s: 'NoneType' object has no attribute 'call'
Traceback (most recent call last):
  File "/home/aayush/yolov9/export.py", line 686, in <module>
    main(opt)
  File "/home/aayush/yolov9/export.py", line 681, in main
    run(**vars(opt))
  File "/home/aayush/miniconda3/envs/yolo9s/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aayush/yolov9/export.py", line 611, in run
    add_tflite_metadata(f[8] or f[7], metadata, num_outputs=len(s_model.outputs))
                                                                ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'outputs'
```

I tried the Useful Links section where I followed the link on how to convert to TFLite model. However, when i try to convert the TFLite model to a RKNN model format i get the following error which means the conversion tool is not able to read the input layers
`AttributeError: 'NoneType' object has no attribute 'get_input_layers'`
I would like to ask when will the export.py file support tflite format ?
Thanks in advance

**Comment by jifeng632** [comment]
same issue here

**Comment by jifeng632** [comment]
![image](https://github.com/WongKinYiu/yolov9/assets/165781509/cbcdd6ef-9161-4a79-ad05-bcedefdaf225)

**Comment by MananGandhi1810** [comment]
any updates upon this?

**Comment by burfom88** [comment]
same issue

**Comment by rgyan619** [comment]
same problem

**Comment by zlelik** [comment]
same for me. Is there a solution for this issue?
