### ISSUE TITLE
’IndexError: list index out of range’ when running val.py with yolov9-c-converted.pt

### ISSUE THREAD

**Issue by Yyc1999super** [WongKinYiu/yolov9#565]

**Comment by Yyc1999super** [comment]
Excuse me, I have the a problem when I convert my yolov9-c.pt to yolov9-c-converted.pt trained on my customizable dataset. 
I used the reparameterization.ipynb's method to convert the yolov9-c to gelan-c, but I saw the ouput of prediction's class is not in the valid sacles.
Traceback (most recent call last):
  File "/home/q/anaconda3/envs/yolov9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/q/anaconda3/envs/yolov9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/q/program/yyccodes/yolov9-main/val.py", line 389, in <module>
    main(opt)
  File "/home/q/program/yyccodes/yolov9-main/val.py", line 362, in main
    run(**vars(opt))
  File "/home/q/anaconda3/envs/yolov9/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/q/program/yyccodes/yolov9-main/val.py", line 244, in run
    save_one_json(predn, jdict, path, class_map)  # append to COCO-JSON dictionary
  File "/home/q/program/yyccodes/yolov9-main/val.py", line 46, in save_one_json
    'category_id': class_map[int(p[5])],
IndexError: list index out of range

**Comment by Yyc1999super** [comment]
**Excuse me, I have the a problem when I convert my yolov9-c.pt to yolov9-c-converted.pt trained on my customizable dataset.
I used the reparameterization.ipynb's method to convert the yolov9-c to gelan-c, but I saw the ouput of prediction's class is not in the valid sacles.**
Traceback (most recent call last):
File "/home/q/anaconda3/envs/yolov9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/q/anaconda3/envs/yolov9/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/main.py", line 39, in
cli.main()
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
run()
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
runpy.run_path(target, run_name="main")
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
return _run_module_code(code, init_globals, run_name,
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
_run_code(code, mod_globals, init_globals,
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
exec(code, run_globals)
File "/home/q/program/yyccodes/yolov9-main/val.py", line 389, in
main(opt)
File "/home/q/program/yyccodes/yolov9-main/val.py", line 362, in main
run(**vars(opt))
File "/home/q/anaconda3/envs/yolov9/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/home/q/program/yyccodes/yolov9-main/val.py", line 244, in run
save_one_json(predn, jdict, path, class_map) # append to COCO-JSON dictionary
File "/home/q/program/yyccodes/yolov9-main/val.py", line 46, in save_one_json
'category_id': class_map[int(p[5])],
IndexError: list index out of range

**Comment by Yyc1999super** [comment]
**Excuse me, I have a problem when I convert my yolov9-c.pt to yolov9-c-converted.pt trained on my customizable dataset.
I used the reparameterization.ipynb's method to convert the yolov9-c to gelan-c, but I saw the ouput of prediction's class is not in the valid sacle**s.
Traceback (most recent call last):
File "/home/q/anaconda3/envs/yolov9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/q/anaconda3/envs/yolov9/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/main.py", line 39, in
cli.main()
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
run()
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
runpy.run_path(target, run_name="main")
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
return _run_module_code(code, init_globals, run_name,
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
_run_code(code, mod_globals, init_globals,
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
exec(code, run_globals)
File "/home/q/program/yyccodes/yolov9-main/val.py", line 389, in
main(opt)
File "/home/q/program/yyccodes/yolov9-main/val.py", line 362, in main
run(**vars(opt))
File "/home/q/anaconda3/envs/yolov9/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/home/q/program/yyccodes/yolov9-main/val.py", line 244, in run
save_one_json(predn, jdict, path, class_map) # append to COCO-JSON dictionary
File "/home/q/program/yyccodes/yolov9-main/val.py", line 46, in save_one_json
'category_id': class_map[int(p[5])],
IndexError: list index out of range

**Comment by Yyc1999super** [comment]
**Excuse me, I have the a problem when I convert my yolov9-c.pt to yolov9-c-converted.pt trained on my customizable dataset.
I used the reparameterization.ipynb's method to convert the yolov9-c to yolov9-c-converted.pt with gelan-c.yaml, but I see the ouput of prediction's class is not in the valid sacles when I run the val.py using the yolov9-c-converted.pt .**
Traceback (most recent call last):
File "/home/q/anaconda3/envs/yolov9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/q/anaconda3/envs/yolov9/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/main.py", line 39, in
cli.main()
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
run()
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
runpy.run_path(target, run_name="main")
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
return _run_module_code(code, init_globals, run_name,
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
_run_code(code, mod_globals, init_globals,
File "/home/q/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
exec(code, run_globals)
File "/home/q/program/yyccodes/yolov9-main/val.py", line 389, in
main(opt)
File "/home/q/program/yyccodes/yolov9-main/val.py", line 362, in main
run(**vars(opt))
File "/home/q/anaconda3/envs/yolov9/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/home/q/program/yyccodes/yolov9-main/val.py", line 244, in run
save_one_json(predn, jdict, path, class_map) # append to COCO-JSON dictionary
File "/home/q/program/yyccodes/yolov9-main/val.py", line 46, in save_one_json
'category_id': class_map[int(p[5])],
IndexError: list index out of range

**Comment by yingziyu11** [comment]
I did the same, using the reparameterization.ipynb method to convert best.pt to best-m-converted.pt, but an error when running val.py.
Traceback (most recent call last):
  File "C:\Users\dl001\anaconda3\envs\yolov9\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\dl001\anaconda3\envs\yolov9\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\msz\yolov9-20240926\utils\plots.py", line 297, in plot_images
    cls = names[cls] if names else cls
KeyError: 6267
                 Class     Images  Instances          P          R      mAP50   mAP50-95:  50%|█████     | 1/2 00:00
Traceback (most recent call last):
  File "test_dual.py", line 393, in <module>
    main(opt)
  File "test_dual.py", line 366, in main
    run(**vars(opt))
  File "C:\Users\dl001\anaconda3\envs\yolov9\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "test_dual.py", line 217, in run
    path, shape = Path(paths[si]), shapes[si][0]
IndexError: list index out of range

**Comment by lc1234567484848** [comment]
是的，我也遇到了这个问题，将yolov9-m转换为yolov9-m-converted后，使用val.py进行验证，报错：                 Class     Images  Instances          P          R      mAP50   mAP50-95:   6%|▋         | 1/16 00:02Exception in thread Thread-4:
Traceback (most recent call last):
  File "E:\Anaconda3\envs\detection\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Anaconda3\envs\detection\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\pythonCode\ObjectDetection\yolov9-main\utils\plots.py", line 297, in plot_images
    cls = names[cls] if names else cls
KeyError: 2683
                 Class     Images  Instances          P          R      mAP50   mAP50-95:  12%|█▎        | 2/16 00:03Exception in thread Thread-6:
Traceback (most recent call last):
  File "E:\Anaconda3\envs\detection\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Anaconda3\envs\detection\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\pythonCode\ObjectDetection\yolov9-main\utils\plots.py", line 297, in plot_images
    cls = names[cls] if names else cls
KeyError: 2683
                 Class     Images  Instances          P          R      mAP50   mAP50-95:  19%|█▉        | 3/16 00:04Exception in thread Thread-8:
Traceback (most recent call last):
  File "E:\Anaconda3\envs\detection\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Anaconda3\envs\detection\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\pythonCode\ObjectDetection\yolov9-main\utils\plots.py", line 297, in plot_images
    cls = names[cls] if names else cls
KeyError: 1423
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 16/16 00:12
                   all        192       4041          0          0          0          0
Speed: 0.6ms pre-process, 47.0ms inference, 1.6ms NMS per image at shape (32, 3, 640, 640)
Results saved to runs\val\exp11
但是经过转换的模型可以用于detect.py进行检测。
