### ISSUE TITLE
question about val.py with yolov9-s-converted.pt

### ISSUE THREAD

**Issue by cxuucx** [WongKinYiu/yolov9#572]
After using the script provided by the author to convert yolov9s to yolov9-s-converted. pt, running val. py will result in the following error:
Traceback (most recent call last):
  File "/home/cx/anaconda3/envs/yolov8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/cx/anaconda3/envs/yolov8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cx/Downloads/yolov9-main/utils/plots.py", line 297, in plot_images
    cls = names[cls] if names else cls
KeyError: 9067
                 Class     Images  Instances          P          R      mAP50   mAP50-95:  10%|█         | 2/20 00:00Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/cx/anaconda3/envs/yolov8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/cx/anaconda3/envs/yolov8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cx/Downloads/yolov9-main/utils/plots.py", line 297, in plot_images
    cls = names[cls] if names else cls
KeyError: 8941
                 Class     Images  Instances          P          R      mAP50   mAP50-95:  20%|██        | 4/20 00:01Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/cx/anaconda3/envs/yolov8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/cx/anaconda3/envs/yolov8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cx/Downloads/yolov9-main/utils/plots.py", line 297, in plot_images
    cls = names[cls] if names else cls
KeyError: 8983
                 Class     Images  Instances          P          R      mAP50   mAP50-95:  95%|█████████▌| 19/20 00:03
Traceback (most recent call last):
  File "val.py", line 389, in <module>
    main(opt)
  File "val.py", line 362, in main
    run(**vars(opt))
  File "/home/cx/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "val.py", line 213, in run
    path, shape = Path(paths[si]), shapes[si][0]
IndexError: list index out of range

**Comment by lc1234567484848** [comment]
您好我也遇到了这个问题，我将yolo-m重新参数化后得到yolo-m-converted，然后使用val.py进行验证，报错：                 Class     Images  Instances          P          R      mAP50   mAP50-95:   6%|▋         | 1/16 00:02Exception in thread Thread-4:
Traceback (most recent call last):
  File "E:\Anaconda3\envs\detection\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Anaconda3\envs\detection\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\pythonCode\ObjectDetection\yolov9-main\utils\plots.py", line 297, in plot_images
    cls = names[cls] if names else cls
KeyError: 2683
                 Class     Images  Instances          P          R      mAP50   mAP50-95:  12%|█▎        | 2/16 00:03Exception in thread Thread-6:
Traceback (most recent call last):
  File "E:\Anaconda3\envs\detection\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Anaconda3\envs\detection\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\pythonCode\ObjectDetection\yolov9-main\utils\plots.py", line 297, in plot_images
    cls = names[cls] if names else cls
KeyError: 2683
                 Class     Images  Instances          P          R      mAP50   mAP50-95:  19%|█▉        | 3/16 00:04Exception in thread Thread-8:
Traceback (most recent call last):
  File "E:\Anaconda3\envs\detection\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Anaconda3\envs\detection\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\pythonCode\ObjectDetection\yolov9-main\utils\plots.py", line 297, in plot_images
    cls = names[cls] if names else cls
KeyError: 1423
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 16/16 00:12
                   all        192       4041          0          0          0          0
Speed: 0.6ms pre-process, 47.0ms inference, 1.6ms NMS per image at shape (32, 3, 640, 640)
Results saved to runs\val\exp11
虽然val.py报错，但是detect.py可以进行检测
