### ISSUE TITLE
RuntimeError: shape '[145, 145, -1]' is invalid for input of size 928000

### ISSUE THREAD

**Issue by PremVarma5142** [WongKinYiu/yolov9#90]
xi.view(feats[0].shape[0], self.no, -1) is resulting in a shape that is inconsistent with the expected shape [145, 145, -1]
```
Traceback (most recent call last):
  File "train_dual.py", line 644, in <module>
    main(opt)
  File "train_dual.py", line 538, in main
    train(opt.hyp, opt, device, callbacks)
  File "train_dual.py", line 315, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/home/raptor1/Downloads/archive(1)/yolov9/utils/loss_tal_dual.py", line 175, in __call__
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
  File "/home/raptor1/Downloads/archive(1)/yolov9/utils/loss_tal_dual.py", line 175, in <listcomp>
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
RuntimeError: shape '[145, 145, -1]' is invalid for input of size 928000
```

**Comment by WongKinYiu** [comment]
Input size should be multiples of 64.

**Comment by anjineyulutv** [comment]
> Input size should be multiples of 64.

What do you mean by that? Input Image?

Can we not use image of any for training? If not let me know how to make it happen

**Comment by PremVarma5142** [comment]
@WongKinYiu  
```
feats = p[1][0] if isinstance(p, tuple) else p[0]
feats2 = p[1][1] if isinstance(p, tuple) else p[1]
original_size = feats[0].shape[0]
new_size = math.ceil(original_size / 64) * 64
```
like this??

**Comment by Kimyuhwanpeter** [comment]
I think, In loss_tal_dual.py
the result of '(line 172) feats = p[1][0] if isinstance(p, tuple) else p[0]' is like [Batch, 16*4+classes, grid_h, grid_w]
so the next line "pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split((self.reg_max * 4, self.nc), 1)" will occur error because feats is not list. so feats must have list(feats)

for example in line 172 in loss_tal_dual.py
feats = p[1][0] if isinstance(p, tuple) else p[0]
feats = list(feats)
...

then there is no error in line 175 in loss_tal_dual.py

please try this

**Comment by Kimyuhwanpeter** [comment]
I think it because of your yaml model.
what did you use?
Please check the yolov9-c.yaml

if you check it
then you can see 
dualDetect branch at the bottom of the yolov9-c.yaml
( [[31, 34, 37, 16, 19, 22], 1, DualDDetect, [nc]],  # DualDDetect(A3, A4, A5, P3, P4, P5) )

and other one, for example, gelan-c.yaml you can not find dual branch. there is only single branch
([[15, 18, 21], 1, DDetect, [nc]],  # DDetect(P3, P4, P5))

so if you want to run like gelan-c.yaml then you shoud use train.py not train_dual.py

**Comment by anjineyulutv** [comment]
I am working on segmentation use case. I am using the corresponding yaml file. But still getting the same error

**Comment by Kimyuhwanpeter** [comment]
@anjineyulutv  Sorry, I mean
1. Select, if you want to train 'dual model'(train_dual.py) or 'single'(train.py)
2. If 'dual model' - please check yaml file for model such as yolov9-c.yaml which is written dualDetect in the file
3. if 'single model' -  please check yaml file for model such as glean-c.yaml is written DDeect or something (you should check the model architecture by yourself).
4. if you check, then please see loss_tal_dual.py and find def __call__() in ComputeLoss. Next, you should debug the if output of the model is listed single or double. if your output have one list for output(only 3 heads) and if the code is connected to loss_tal_dual.py then you should change model to dual model.
(these errors occur in ' pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split((self.reg_max * 4, self.nc), 1) '

so you should first check that pred from model(img) is consist of one or two list.

**Comment by anjineyulutv** [comment]
I appreciate the detailed effort to explain!!!.There is no such keyword in yaml file of yolov7-af-seg.yaml.And got your intuition and there no such operator with dual prefix. Thus I am goin with train.py.
I assume this holds for all the models as standard convention for yolov9

**Comment by WongKinYiu** [comment]
For training `yolov7-af-seg.yaml`, please use `segment/train.py`.

**Comment by anjineyulutv** [comment]
Thanks,where can I find yolo-seg.pt
